version: 2
sources:
  - name: raw_ingest
    database: nordic-retail-intel-2025
    schema: raw_ingest
    tables:
      - name: eurostat_retail_trade
      - name: eurostat_ecommerce
      - name: eurostat_consumer_confidence
      - name: eurostat_individuals_buying_online
      - name: eurostat_online_purchase_frequency
      - name: national_stats_retail_trade
      - name: weather_daily
      - name: google_trends_top_terms
      - name: google_trends_rising_terms
      - name: folkhalsomyndigheten_nicotine
      - name: ssb_nicotine_demographics_no
      - name: google_trends_nicotine_weekly
      - name: google_trends_nicotine_by_region
